apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsimplestorages.caiofralmeida.io
spec:
  group: caiofralmeida.io
  names:
    kind: xSimpleStorage
    plural: xsimplestorages
  claimNames:
    kind: SimpleStorage
    plural: simplestorages
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              area:
                type: string
              tags:
                type: object
                additionalProperties:
                  type: string
          status:
            type: object
            properties:
              id:
                type: string
