apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    crossplane.io/xrd: xxrdgenerators.crossplane.caiofralmeida.io
  name: xxrdgenerators.crossplane.caiofralmeida.io
spec:
  compositeTypeRef:
    apiVersion: crossplane.caiofralmeida.io/v1alpha1
    kind: xXRDGenerator
  patchSets:
  - name: name
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.labels[crossplane.io/claim-name]
      toFieldPath: spec.forProvider.manifest.metadata.name
  - name: namespace
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
      toFieldPath: spec.forProvider.manifest.metadata.namespace
  resources:
  - name: cm
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        deletionPolicy: Delete
        forProvider:
          manifest:
            apiVersion: v1
            kind: ConfigMap
            data:
              def: ""
    patches:
    - type: PatchSet
      patchSetName: name
    - type: PatchSet
      patchSetName: namespace

    - type: CombineFromComposite
      combine:
        variables:
          - fromFieldPath: spec.resourceName
          - fromFieldPath: spec.specFields
          - fromFieldPath: spec.specStatus
        strategy: string
        string:
          fmt: "fobarr"
            
      toFieldPath: spec.forProvider.manifest.data.def
