apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    crossplane.io/xrd: xxrdgenerators.crossplane.caiofralmeida.io
  name: xxrdgenerators.crossplane.caiofralmeida.io
spec:
  compositeTypeRef:
    apiVersion: crossplane.caiofralmeida.io/v1alpha1
    kind: xXRDGenerator
  mode: Pipeline
  pipeline:
  - step: testing-go-templating
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          apiVersion: kubernetes.crossplane.io/v1alpha1
          kind: Object
          metadata:
            annotations:
              {{ setResourceNameAnnotation "test" }}
          spec:
            deletionPolicy: Delete
            forProvider:
              manifest:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: foo
                  namespace: default 
                data:
                  def: {{ .observed.composite.resource.spec.resourceName }}


