apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xxrdgenerators.crossplane.caiofralmeida.io
spec:
  group: crossplane.caiofralmeida.io
  names:
    kind: xXRDGenerator
    plural: xxrdgenerators
  claimNames:
    kind: XRDGenerator
    plural: xrdgenerators
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              resourceName:
                type: string
              specFields:
                type: object
                additionalProperties:
                  type: string
              statusFields:
                type: object
                additionalProperties:
                  type: string

